// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8KTwRMCo7fWC5-D428qq8b9OS6Vv_GkQ',
    appId: '1:997488368829:android:b01a3e6be2d6db3faf2bd4',
    messagingSenderId: '997488368829',
    projectId: 'social-app-9458e',
    databaseURL: 'https://social-app-9458e.firebaseio.com',
    storageBucket: 'social-app-9458e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmaW1ql4Qpgf99rMcJ3yuuTCmEKL7E-Nk',
    appId: '1:997488368829:ios:a4bed8618943962eaf2bd4',
    messagingSenderId: '997488368829',
    projectId: 'social-app-9458e',
    databaseURL: 'https://social-app-9458e.firebaseio.com',
    storageBucket: 'social-app-9458e.appspot.com',
    androidClientId: '997488368829-bahm2foicnar0f4e5ua5i4ctve24ja40.apps.googleusercontent.com',
    iosClientId: '997488368829-mqcs9t1q9pkh8dks779ng4vk5al6sja7.apps.googleusercontent.com',
    iosBundleId: 'com.example.dicodingDitonton',
  );
}
